<h1 align = "center">Introduction to TensorFlow (TF)</h1>

---

**Course Name:** [Learning TensorFlow and Deep Learning Fundamentals with _python_](https://www.youtube.com/playlist?list=PL6vjgQ2-qJFfU2vF6-lG9DlSa4tROkzt9) - the series is an introductory, and _prerequisites_ for TF Developer Certificate Course by ZTM (udemy/ZTM website). Things covered in this section are:

* Introduction to _tensors_
* Getting Information from _tensors_
* Manipulating _tensors_
* Tensors vs. NumPy
* Using `@tf.function` (to speed up python functions)

In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.1


**TF** works best with GPUs (or TPUs), and the following cell can be executed to check if GPU is available, and is CUDA version is supported.

In [6]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]

## Introduction to _tensors_

In [8]:
# constant/scalar
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [9]:
# constant/vector
vector = tf.constant([7, 7])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7])>, 1)

In [13]:
# variables
var = tf.Variable(7, name = "variable", dtype = tf.float64)
var

<tf.Variable 'variable:0' shape=() dtype=float64, numpy=7.0>

In [16]:
# random tensors
matrix = tf.random.normal(shape = (3, 2, 3), dtype = tf.float64)
matrix, matrix.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
 array([[[ 0.63920069, -0.477676  ,  1.6661794 ],
         [ 0.76748898,  0.28904098,  1.43272162]],
 
        [[ 1.57410859,  0.2370801 ,  1.65483147],
         [-0.74592991, -0.12261321, -0.15311184]],
 
        [[ 0.4826045 ,  0.03997786, -1.96221099],
         [-1.28835394,  0.56510965,  0.99202599]]])>,
 3)