**Objective:** The _notebook_ presents the method to prepare the features and labels for a _time series machine learning model_ using the `tensorflow` library. Typically, for a time series problem the features and the output is a sequence of values, where features are, for example, like $x_0, x_1, ..., x_{n-1}$ and output is $y = x_n$ for one time step. This can be developed as:

In [1]:
import numpy as np

In [2]:
import tensorflow as tf
print(f"Tensorflow Version: {tf.__version__}")

tf.config.list_physical_devices()

Tensorflow Version: 2.9.0


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [23]:
dataset = tf.data.Dataset.range(10) # create a tf with elements 0 to 10
type(dataset), [(x.numpy(), type(x)) for x in dataset]

(tensorflow.python.data.ops.dataset_ops.RangeDataset,
 [(0, tensorflow.python.framework.ops.EagerTensor),
  (1, tensorflow.python.framework.ops.EagerTensor),
  (2, tensorflow.python.framework.ops.EagerTensor),
  (3, tensorflow.python.framework.ops.EagerTensor),
  (4, tensorflow.python.framework.ops.EagerTensor),
  (5, tensorflow.python.framework.ops.EagerTensor),
  (6, tensorflow.python.framework.ops.EagerTensor),
  (7, tensorflow.python.framework.ops.EagerTensor),
  (8, tensorflow.python.framework.ops.EagerTensor),
  (9, tensorflow.python.framework.ops.EagerTensor)])

In [24]:
dataset = dataset.window(5, shift = 1, drop_remainder = True)

In [25]:
for window in dataset:
    for array in window:
        print(array.numpy(), end = " ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [26]:
dataset = dataset.flat_map(lambda window : window.batch(5)) # collate elements
[window.numpy() for window in dataset]

[array([0, 1, 2, 3, 4], dtype=int64),
 array([1, 2, 3, 4, 5], dtype=int64),
 array([2, 3, 4, 5, 6], dtype=int64),
 array([3, 4, 5, 6, 7], dtype=int64),
 array([4, 5, 6, 7, 8], dtype=int64),
 array([5, 6, 7, 8, 9], dtype=int64)]

In [27]:
# now map the corresponding `x` and `y` values
dataset = dataset.map(lambda window : (window[:-1], window[-1]))

for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


In [28]:
# shuffle the dataset using the `.shuffle`
dataset = dataset.shuffle(buffer_size = 10)

for x, y in dataset:
    print(x.numpy(), y.numpy())

[1 2 3 4] 5
[5 6 7 8] 9
[4 5 6 7] 8
[0 1 2 3] 4
[3 4 5 6] 7
[2 3 4 5] 6


In [29]:
# batch the data using `.batch` followed by `.prefetch`
dataset = dataset.batch(2).prefetch(1)

for x, y in dataset:
    print(f"<x = {x.numpy()}, y = {y.numpy()}>")

<x = [[5 6 7 8]
 [2 3 4 5]], y = [9 6]>
<x = [[4 5 6 7]
 [3 4 5 6]], y = [8 7]>
<x = [[0 1 2 3]
 [1 2 3 4]], y = [4 5]>


Combining the above knowledge, let's create a general dynamic function that can be used for all type of analysis.

In [3]:
def create_xy(series : np.ndarray, window_size : int, batch_size : int, shuffle_buffer : int, **kwargs):
    """
    Process a `np.ndarray` into XY Lables for AI-ML Time Series Analysis
    
    Consider a 1D-Array the data splits and process it into `xy` where `x` is
    the number of features set by the "window" element and `y` is the last
    element for each data split. For detailed methodlogies check each
    steps as dicussed above.
    """
    
    dataset = tf.data.Dataset.from_tensor_slices(series)
    dataset = dataset.window(window_size + 1, shift = kwargs.get("shift", 1), drop_remainder = True)
    dataset = dataset.flat_map(lambda window : window.batch(window_size + 1))
    dataset = dataset.shuffle(shuffle_buffer).map(lambda window : (window[:-1], window[-1]))
    
    return dataset.batch(batch_size).prefetch(1)

In [4]:
WINDOW, BATCH, SHUFFLE = 5, 3, 20

In [5]:
series = np.random.randint(0, 101, size = (30, 5))
dataset = create_xy(series, window_size = WINDOW, batch_size = BATCH, shuffle_buffer = SHUFFLE)

for x, y in dataset:
    print(f"<x = {x.numpy()}, y = {y.numpy()}>")

<x = [[[66 61 75 23 36]
  [54 50 41  8 31]
  [55 19 35  7  0]
  [76 67 63 43  2]
  [44 12 99 82 25]]

 [[89 68 57 97 11]
  [99  8 48 26 86]
  [45 99 77 53 25]
  [21 50 91 82 84]
  [79 61 14 65 83]]

 [[90 95 19 98 34]
  [64 87 86 88 92]
  [40 96 68 49 40]
  [66 61 75 23 36]
  [54 50 41  8 31]]], y = [[17 59 16 46 83]
 [37 53 97 66 26]
 [55 19 35  7  0]]>
<x = [[[ 55  19  35   7   0]
  [ 76  67  63  43   2]
  [ 44  12  99  82  25]
  [ 17  59  16  46  83]
  [ 36   1  28  55  78]]

 [[ 34  34  37  74 100]
  [ 83  69  93  51  37]
  [ 88  39  25  16  66]
  [ 80  65  86  15   5]
  [ 14  77  62  56  57]]

 [[ 17  59  16  46  83]
  [ 36   1  28  55  78]
  [ 72  51  38  64  65]
  [ 73  46  33  59  87]
  [ 99  73  28  78  79]]], y = [[72 51 38 64 65]
 [32 37 19 27 71]
 [45  4  7 78 86]]>
<x = [[[59 96 83 68 61]
  [19 57 40 29  6]
  [54 48 62 12 36]
  [ 4 64 31 75 10]
  [90 95 19 98 34]]

 [[54 48 62 12 36]
  [ 4 64 31 75 10]
  [90 95 19 98 34]
  [64 87 86 88 92]
  [40 96 68 49 40]]

 [[80 65 86 